version: '3.8'

services:
  postgres-clearinghouse:
    image: postgres:15
    container_name: postgres-clearinghouse
    environment:
      POSTGRES_DB: clearinghouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_clearinghouse_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clearinghouse"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-billing:
    image: postgres:15
    container_name: postgres-billing
    environment:
      POSTGRES_DB: billing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_billing_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d billing"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_clearinghouse_data:
  postgres_billing_data: